### ISSUE TITLE
Html Output.

### ISSUE THREAD

**Issue by iowyncrox** [cucumber/cucumber-electron#17]
How to run cucumber-electron to get HTML output? What are the different ways to get HTML output?

https://github.com/iowyncrox/cucumberelectron sample repo

https://github.com/iowyncrox/cucumberelectron/blob/master/renderer.js Line 11: Code to run cucumber-electron.

Goal:

    Click a button on a webpage A.
    OnClick: execute the cucumber feature file in the background and get the output in HTML format.
    Show the HTML generated by cucumber on the same webpage A.

**Comment by joshski** [comment]
cucumber-electron runs inside a node process with a DOM. To use cucumber-electron you don't 
need to create an electron app yourself. You just need to write feature files and step definitions.

Since cucumber-electron is essentially a wrapper for cucumber-js, your options for HTML output are the same as in cucumber-js. You need a formatter that renders HTML. This looks like it does the job: https://github.com/gkushang/cucumber-html-reporter
