### ISSUE TITLE
Electron pinned to restrictively

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-electron#57]
I'd like to use Electron 11.1.0 (currently latest), but `package.json` doesn't allow anything greater than `11.0.3`. Is there a particular reason for this restriction?

npm 6 would let you install a higher version, but npm 7 disallows it...

**Comment by jbpros** [comment]
I pinned the peerDependency to the highest specific version used during builds, I think that can be relaxed a bit.

**Comment by jbpros** [comment]
Fixed in f9aa21cdd1dc829384692d415458252e70fb1df4.

I bumped Electron to 11.1.0 about 10 minutes ago. I then run `npm run update-dependencies` to make a release and noticed electron 11.1.1... It was released 5 minutes ago 😅 So yeah, relaxing this peer dependency version is probably a good idea. Thanks for the issue.

**Comment by jbpros** [comment]
And this has been released with 3.0.0!
