### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-electron#65]
As #58 suggests, the name `@cucumber/electron` leads people to believe that this is a module for testing Electron applications, or that it requires writing Electron code.

This is not the case - electron is an opaque implementation detail of this module. It's a module geared towards testing "DOM applications" such as React, Vue, Svelte or anything that runs in a normal browser.

There is one important distinction - the code being tested has access to the DOM, but it isn't intended to be used as a browser with full access to `HTTP`, `window.location` etc. Well, you do have access to these, but using them defeats the purpose of this library: Acceptance testing of "DOM" code.

What about `@cucumber/dom` or `@cucumber/interactive`?

**Comment by aslakhellesoy** [comment]
BTW, I've found `@cucumber/electron` useful even when I'm not working with DOM code, because of the interactive debugger. Lots of people use editors with poor support for debugging JavaScript code, and `@cucumber/electron` helps a lot.

Something to keep in mind for a name suggestion - it's not DOM only.

**Comment by mattwynne** [comment]
I think this is a good idea, and I think it's worth careful consideration to name this thing well. It's an _amazing_ tool, once you figure out how to use it, so good branding will help it to reach the right audience.

**Comment by mattwynne** [comment]
At the moment it had quite an inward-facing name - accurate as to what it's made of, but not illustrative of what it can do. IMO we need to think more about what it can do for people and name it after that. Or find a random name akin to Selenium / Cypress because that's the kind of space it operates in.

**Comment by aurelien-reeves** [comment]
`cucumber-gui`?

**Comment by cbliard** [comment]
is it limited to cucumber-js?

**Comment by aurelien-reeves** [comment]
> 
> 
> `cucumber-gui`?

Or more mdern variants:
- cucumber-dekstop
- cucumber-desktop-app
- cucumber-app

> 
> 
> is it limited to cucumber-js?

It seems to be, yes.

**Comment by jbpros** [comment]
> Or find a random name akin to Selenium / Cypress because that's the kind of space it operates in.

I think @aslakhellesoy has got a point about cucumber-electron not being only useful for DOM-based automation and the name of the project could reflect that. We could even take it into the direction of a general cucumber GUI compatible with more than just Cucumber.js.

**Comment by cbliard** [comment]
Our original name during [January 2020 hackathon](https://miro.com/app/board/o9J_kv2cI_M=/?moveToWidget=3074457347142335732&cot=14) was cukui :)

**Comment by mattwynne** [comment]
Is there a way we could bundle this thing *with* cucumber-js, so it just became additional functionality of that package?

**Comment by aslakhellesoy** [comment]
Interesting idea!

The simple way to do it would be to add a dependency from `cucumber-js` to `cucumber-electron`, but that wouldn't work well in practice because of circular dependencies between the two projects. It's a recipe for disaster.

If we really want to go down the route of making this available to all `cucumber-js` users, I think we should simply move all the code into the `cucumber-js` codebase.

The dependency on `electron` is a peer dependency, so it wouldn't force people to install `electron`.

If we did this, what are your thoughts about making users discover that it exists? How would this be better than installing it separately as you have to do now?

**Comment by mattwynne** [comment]
> If we did this, what are your thoughts about making users discover that it exists? How would this be better than installing it separately as you have to do now?

I guess it would be easier for people to bump into it via reading the docs for cucumber-js, for one thing. It just also seems simpler to explain to people "cucumber-js can now test your single-page-apps" rather than "we have this other thing that wraps cucumber-js that you can use to test your single-page apps"

**Comment by cbliard** [comment]
> It just also seems simpler to explain to people "cucumber-js can now test your single-page-apps" rather than "we have this other thing that wraps cucumber-js that you can use to test your single-page apps"

I like this point of view.

If embedding cucumber-electron into cucumber-js, would it have an impact about managing dependencies conflicts for projects already using electron and using cucumber-js for their automation?

**Comment by aslakhellesoy** [comment]
CE has a peer dependency on `electron`, so it wouldn't conflict.

**Comment by aslakhellesoy** [comment]
I had a conversation with @tooky about this day, and he asked me an intriguing question:

> Could we make a Visual Studio Code plugin?

Visual Studio Code uses Electron as its runtime platform, so plugins have access to Node.js libraries as well as the DOM.

A VS code Cucumber Plugin could reuse most of the code from this library, and could provide a seamless developer experience for:

* Writing scenarios
* Running scenarios
* UI Automation

This would be a developer experience similar to that offered by Cypress. The main difference would be that the UI doesn't run in a full browser environment - there won't be a regular `window.location`, nor will there be cookies. This means the code under test (React/Vue components) would have to be decoupled from the browser APIs that are not available (but they could still use the DOM of course).

This means a slightly higher barrier to entry than for Cypress, since it requires users to decouple their SPA code from the browser. The entry point would be a *component* and not a *page*. This is also a prerequisite for having blazing fast UI tests, which is why this library exists in the first place. We already have #58 which covers that.

**Comment by mattwynne** [comment]
It's also possible to run a full SPA in an iFrame, is it not? I feel like we did a proof of concept around this before.

**Comment by mattwynne** [comment]
Yes, [this](https://github.com/cucumber/cucumber-electron/blob/main/examples/angularjs/features/step_definitions/steps.js#L15).

Could we not use something like that so people could mount a full app? Otherwise it seems to me this is going to be too difficult for people to grok and use. Unfortunately the kind of decoupling you're talking about is really niche.

**Comment by aslakhellesoy** [comment]
> It's also possible to run a full SPA in an iFrame, is it not? 

Oh yes @mattwynne I hadn't thought of that. Brilliant! So by using an iframe we could also support testing of monolithic web apps.

And for people who know the decoupling chops, they don't need to use an iframe. Brilliant!

**Comment by joshski** [comment]
> So by using an iframe we could also support testing of monolithic web apps.

I once used cucumber-electron against a traditional, non-SPA,
server-rendered web app (developed in rails but with some critical
angular code on individual pages) running each scenario in an iframe
with a hook into the web app to set up state before each scenario.

There are some challenges around cross-domain security and shared
state between scenarios (since each scenario uses the same hostname
and therefore cookies etc), but we still got a lot of value out of it.
Understanding these challenges is not easy though IMO.

**Comment by aurelien-reeves** [comment]
So, nothing new since a while now.
Any new ideas? Should we process to a vote or something?

I was able to find the following propositions:

@cucumber/dom
@cucumber/interactive
@cucumber/gui
@cucumber/dekstop
@cucumber/desktop-app
@cucumber/app
cukui

I could post each as a comment to that issue, and people may vote using 👍 reactions?

**Comment by mattwynne** [comment]
@aurelien-reeves my sense of the way this conversation went was that we'd decided that rolling this project into cucumber-js would be the best idea.

**Comment by aurelien-reeves** [comment]
Oh, yes! Forgot that part.

Could we then open an issue - or a PR - in cucumber-js to make sure the idea is accepted there? Then we may be able to close this issue?

**Comment by mattwynne** [comment]
Done: https://github.com/cucumber/cucumber-js/issues/1799
